-- MySQL Script generated by MySQL Workbench
-- Fri Jun  5 10:04:42 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema SGCSenac
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `SGCSenac`;
CREATE SCHEMA IF NOT EXISTS `SGCSenac` ;
USE `SGCSenac` ;

-- -----------------------------------------------------
-- Table `SGCSenac`.`Categoria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SGCSenac`.`Categoria` ;

CREATE TABLE IF NOT EXISTS `SGCSenac`.`Categoria` (
  `idCategoria` BIGINT NOT NULL AUTO_INCREMENT,
  `nomeCategoria` VARCHAR(45) NOT NULL,
  `descricaoCategoria` VARCHAR(100),
  `estado` TINYINT NULL DEFAULT 1,
  PRIMARY KEY (`idCategoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SGCSenac`.`ProdutoLog`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SGCSenac`.`ProdutoLog` ;

CREATE TABLE IF NOT EXISTS `SGCSenac`.`ProdutoLog` (
  `idProdutoLog` BIGINT NOT NULL AUTO_INCREMENT,
  `idProdutos` BIGINT NOT NULL,
  `nomeOld` VARCHAR(45) NULL,
  `descricaoOld` VARCHAR(100) NULL,
  `quantidadeOld` INT NULL,
  `unidade` varchar(2) NULL,
  `precoOld` DECIMAL NULL,
  `estadoOld` TINYINT NULL,
  `dataLog` DATETIME NOT NULL DEFAULT now(),
  `idUsuarioAutor` BIGINT NOT NULL DEFAULT -1,
  PRIMARY KEY (`idProdutoLog`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SGCSenac`.`Usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SGCSenac`.`Usuario` ;

CREATE TABLE IF NOT EXISTS `SGCSenac`.`Usuario` (
  `idUsuario` BIGINT NOT NULL AUTO_INCREMENT,
  `numIdentificacao` INT NOT NULL,
  `nomeUsuario` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `telefone` VARCHAR(45) NULL,
  `cargo` INT NOT NULL COMMENT 'Cargos: 1 = usuário | 0 = administrador',
  `senha` VARCHAR(100) NULL,
  `estado` TINYINT NULL DEFAULT 1,
  `updateID` BIGINT NOT NULL DEFAULT -1,
  PRIMARY KEY (`idUsuario`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `numIdentificacao_UNIQUE` (`numIdentificacao` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SGCSenac`.`Pedido`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SGCSenac`.`Pedido` ;

CREATE TABLE IF NOT EXISTS `SGCSenac`.`Pedido` (
  `idPedido` BIGINT NOT NULL AUTO_INCREMENT,
  `statusPedido` INT NOT NULL DEFAULT 0,
  `dataPedido` DATETIME NOT NULL DEFAULT now(),
  `Usuario_idUsuario` BIGINT NOT NULL,
  PRIMARY KEY (`idPedido`),
  INDEX `fk_Pedido_Usuario1_idx` (`Usuario_idUsuario` ASC) VISIBLE,
  CONSTRAINT `fk_Pedido_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `SGCSenac`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SGCSenac`.`Produtos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SGCSenac`.`Produtos` ;

CREATE TABLE IF NOT EXISTS `SGCSenac`.`Produtos` (
  `idProdutos` BIGINT NOT NULL AUTO_INCREMENT,
  `nomeProduto` VARCHAR(45) NOT NULL,
  `descricaoProduto` VARCHAR(100),
  `quantidadeEstoque` INT NOT NULL,
  `unidade` VARCHAR(2) NULL, 
  `Categoria_idCategoria` BIGINT NOT NULL,
  `ultimaAtualizacao` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `precoProduto` DECIMAL NULL,
  `estado` TINYINT NULL DEFAULT 1,
  `updateID` BIGINT NOT NULL DEFAULT -1,
  PRIMARY KEY (`idProdutos`),
  INDEX `fk_Produtos_Categoria_idx` (`Categoria_idCategoria` ASC) VISIBLE,
  CONSTRAINT `fk_Produtos_Categoria`
    FOREIGN KEY (`Categoria_idCategoria`)
    REFERENCES `SGCSenac`.`Categoria` (`idCategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SGCSenac`.`ItensPedido`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SGCSenac`.`ItensPedido` ;

CREATE TABLE IF NOT EXISTS `SGCSenac`.`ItensPedido` (
  `idItensPedido` BIGINT NOT NULL AUTO_INCREMENT,
  `Produtos_idProdutos` BIGINT NOT NULL,
  `Pedido_idPedido` BIGINT NOT NULL,
  `quantidade` INT NOT NULL,
  `precoUnitario` DECIMAL(10,2),
  PRIMARY KEY (`idItensPedido`),
  INDEX `fk_ItensPedido_Produtos1_idx` (`Produtos_idProdutos` ASC) VISIBLE,
  INDEX `fk_ItensPedido_Pedido1_idx` (`Pedido_idPedido` ASC) VISIBLE,
  CONSTRAINT `fk_ItensPedido_Produtos1`
    FOREIGN KEY (`Produtos_idProdutos`)
    REFERENCES `SGCSenac`.`Produtos` (`idProdutos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ItensPedido_Pedido1`
    FOREIGN KEY (`Pedido_idPedido`)
    REFERENCES `SGCSenac`.`Pedido` (`idPedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SGCSenac`.`UsuarioLog`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SGCSenac`.`UsuarioLog` ;

CREATE TABLE IF NOT EXISTS `SGCSenac`.`UsuarioLog` (
  `idUsuarioLog` BIGINT NOT NULL AUTO_INCREMENT,
  `idUsuario` BIGINT NOT NULL DEFAULT -1,
  `nomeOld` VARCHAR(45) NULL,
  `cargoOld` INT NULL,
  `estadoOld` TINYINT NULL,
  `dataLog` DATETIME NOT NULL DEFAULT now(),
  `idUsuarioAutor` BIGINT NOT NULL,
  PRIMARY KEY (`idUsuarioLog`))
ENGINE = InnoDB;

USE `SGCSenac` ;

-- -----------------------------------------------------
-- View `SGCSenac`.`PEDIDO`
-- -----------------------------------------------------
DROP VIEW IF EXISTS `SGCSenac`.`VIEW_PEDIDO` ;
USE `SGCSenac`;
CREATE  OR REPLACE VIEW `VIEW_PEDIDO` AS
select p.idPedido as ID, u.nomeUsuario as Funcionario, p.statusPedido as "Status", pr.nomeProduto as Produto from Pedido p
left join Usuario u on u.idUsuario = p.Usuario_idUsuario 
left join ItensPedido i on i.Pedido_idPedido = p.idPedido
left join Produtos pr on pr.idProdutos = i.Produtos_idProdutos
;

-- -----------------------------------------------------
-- View `SGCSenac`.`ViewDetalhesPedido`
-- -----------------------------------------------------
DROP VIEW IF EXISTS `SGCSenac`.`ViewDetalhesPedido` ;
USE `SGCSenac`;
CREATE  OR REPLACE VIEW `ViewDetalhesPedido` AS
SELECT p.idPedido as ID, u.nomeUsuario as Funcionario, pr.nomeProduto as Produto, i.quantidade as Quantidade, 
	(i.precoUnitario * i.quantidade) as "Subtotal", p.dataPedido as "Data", 
    p.statusPedido as "Status"
from Pedido p
inner join Usuario u on u.idUsuario = p.Usuario_idUsuario
inner join ItensPedido i on i.Pedido_idPedido = p.idPedido
inner join Produtos pr on pr.idProdutos = i.Produtos_idProdutos;
USE `SGCSenac`;

DELIMITER $$

USE `SGCSenac`$$
DROP TRIGGER IF EXISTS `SGCSenac`.`Produtos_BEFORE_UPDATE` $$
USE `SGCSenac`$$
CREATE DEFINER = CURRENT_USER TRIGGER `SGCSenac`.`Produtos_BEFORE_UPDATE` BEFORE UPDATE ON `Produtos` FOR EACH ROW
BEGIN
	insert into `SGCSenac`.`ProdutoLog` (idProdutos, nomeOld, descricaoOld, quantidadeOld, unidade, precoOld, estadoOld, idUsuarioAutor) values (
		OLD.idProdutos,
		OLD.nomeProduto,
        OLD.descricaoProduto,
        OLD.quantidadeEstoque,
        OLD.unidade,
        OLD.precoProduto,
        OLD.estado,
        NEW.updateID
    );
END$$


USE `SGCSenac`$$
DROP TRIGGER IF EXISTS `SGCSenac`.`Usuario_BEFORE_UPDATE` $$
USE `SGCSenac`$$
CREATE DEFINER = CURRENT_USER TRIGGER `SGCSenac`.`Usuario_BEFORE_UPDATE` BEFORE UPDATE ON `Usuario` FOR EACH ROW
BEGIN
	insert into `SGCSenac`.`UsuarioLog` (idUsuario, nomeOld, cargoOld, estadoOld, idUsuarioAutor) values (
		OLD.idUsuario,
		OLD.nomeUsuario,
        OLD.cargo,
        OLD.estado,
        NEW.updateID
    );
END$$


DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;




-- -----------------------------------------------------
-- INSERTS PARA TESTES: 
-- 	TODAS AS SENHAS SÃO "12345" caso precise fazer testes de login ou alteração de senha
-- -----------------------------------------------------

INSERT INTO `Usuario` (`numIdentificacao`, `nomeUsuario`, `email`, `telefone`, `cargo`, `senha`, `estado`) VALUES
(2001, 'Alice Martins', 'alice.martins@empresa.com', '44999990001', 1, '$2a$10$Tnlqy/PlBFb10A1/g8/k2.zkWXotDwFOkzOrn.VSyJoSqtnEzH8g.', 1),
(2002, 'Bruno Costa', 'bruno.costa@empresa.com', '44999990002', 2, '$2a$10$iMBsnDvCJ2Y5mdLz2z2nK.XynXr6CIjT2/mMn28NJuufZFY.Q3YeS', 1),
(2003, 'Carla Dias', 'carla.dias@empresa.com', NULL, 1, '$2a$10$eCkciKoiZjP8/JmcSPpKmOmsLXpx6NHPM5HzLTMVlq2pML6fQps4m', 1),
(2004, 'Diogo Silva', 'diogo.silva@empresa.com', '44999990004', 1, '$2a$10$A/s3biiSatjg1DtWiuZAm.VC32vmVAfqbYA3wmwrKSdmxrvDcK4mi', 0),
(2005, 'Elisa Gomes', 'elisa.gomes@empresa.com', '44999990005', 1, '$2a$10$C8MwRZLLX6dfA1UMrWlQd.6muvZm9CBdt.5uz2L1HXHk.K5xrhhky', 1),
(2006, 'Fabio Rocha', 'fabio.rocha@empresa.com', NULL, 2, '$2a$10$EL.ulqopwVs3pFJVk9Hrg.yf7WDC3lWI5K9wwab8VS/7o62rPBygq', 1),
(2007, 'Gabriela Mendes', 'gabriela.mendes@empresa.com', '44999990007', 1, '$2a$10$VLJlr3a34AOpVkoVqDEOUewFHwKdDWLGXAWUcvuUKbMzfSBMUzAni', 1),
(2008, 'Hugo Alves', 'hugo.alves@empresa.com', '44999990008', 1, '$2a$10$38wbpw8YfBVbWRgAMU99NOqsT2AC99FTv29J8hAAgatk31G8PT34a', 0),
(2009, 'Igor Castro', 'igor.castro@empresa.com', NULL, 1, '$2a$10$5vsH6EmKfD0hed7Vd0bc5.wHr3HxaIEb0Sa1hOJNn96SBtMYXvWUu', 1),
(2010, 'Julia Nunes', 'julia.nunes@empresa.com', '44999990010', 2, '$2a$10$vHzVEyE75pUsvn5Ucq4odOQc52WGmKqQte6NHSWz.2vhNfuOxuSOe', 1),
(2011, 'Kleber Lima', 'kleber.lima@empresa.com', '44999990011', 1, '$2a$10$oInLUwBGFMJ.otPfobHQW.aGE53Qridq8qF1Jr.Ayeqc.v0u1KgQ6', 1),
(2012, 'Larissa Pires', 'larissa.pires@empresa.com', '44999990012', 1, '$2a$10$uuBHmZxwMAVBySGNoP4.5uf1DunKu99rt81kUGupYpDO3QE0CgkuW', 1),
(2013, 'Marcos Faria', 'marcos.faria@empresa.com', NULL, 1, '$2a$10$zMH1U5EZ/YJjvwcvnrmYDOasSkAbMc7OCSwbKEBwV0Ay/mD87M73q', 0),
(2014, 'Natalia Moura', 'natalia.moura@empresa.com', '44999990014', 1, '$2a$10$oUQY9KzC36UWOgqeWMtctuvW7m/eJD1YSdJCCHjiWV5evvUTm8geO', 1),
(2015, 'Otavio Reis', 'otavio.reis@empresa.com', '44999990015', 1, '$2a$10$GSAtj4gZGE6FATtUWxVgVuY8vMLJdOxiBy1GvDY7XV5P6qWt1rv2a', 1),
(2016, 'ADM', 'adm@empresa.com', '44999990016', 0, '$2a$10$GSAtj4gZGE6FATtUWxVgVuY8vMLJdOxiBy1GvDY7XV5P6qWt1rv2a', 1);



INSERT INTO `SGCSenac`.`Categoria` (`nomeCategoria`, `descricaoCategoria`, `estado`) VALUES
('Informática', 'Equipamentos e componentes de computador', 1),
('Papelaria', 'Materiais de escritório e consumíveis', 1),
('Limpeza', 'Produtos de higienização e manutenção', 1),
('Mobiliário', 'Mesas, cadeiras e estantes', 1);


SELECT p.idProdutos, p.nomeProduto, p.descricaoProduto, p.precoProduto, p.quantidadeEstoque, p.unidade, p.estado AS estadoProduto, c.idCategoria, c.nomeCategoria, c.descricaoCategoria, c.estado AS estadoCategoria
FROM Produtos p
INNER JOIN Categoria c ON p.Categoria_idCategoria = c.idCategoria
ORDER BY p.idProdutos ASC;