package Telas;

import DAO.UsuarioDao;
import Model.Usuario;
import javax.swing.*;
import javax.swing.plaf.FontUIResource;
import javax.swing.text.StyleContext;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.Locale;
import java.util.Optional;

public class Login extends JFrame {
    private JPanel panel1;
    private JButton EntrarBT;
    private JLabel usuarioCracha;
    private JTextField usuarioTF;
    private JLabel senhaLabel;
    private JPasswordField senhaTF;
    private JLabel cadastrarLabel;


    public Login() {
        setContentPane(panel1);
        setTitle("SGC Senac - Login");
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setSize(400, 350);
        setLocationRelativeTo(null);
        getRootPane().setDefaultButton(EntrarBT);

        cadastrarLabel.setText("<html><u>Não tem uma conta ainda? Cadastrar!</u></html>");
        cadastrarLabel.setForeground(Color.BLUE);
        cadastrarLabel.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));

        cadastrarLabel.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                new FuncionariosCadastro();
            }
        });

        setVisible(true);

        EntrarBT.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                fazerLogin();
            }
        });
    }

    private void fazerLogin() {
        try {
            int cracha = Integer.parseInt(usuarioTF.getText());
            String senhaDigitada = new String(senhaTF.getPassword());

            UsuarioDao dao = new UsuarioDao();
            Optional<Usuario> usuarioOpt = dao.buscarPorCracha(cracha);

            if (usuarioOpt.isPresent()) {
                Usuario usuarioEncontrado = usuarioOpt.get();

                if (dao.checarSenha(senhaDigitada, usuarioEncontrado.getSenha())) {
                    if (usuarioEncontrado.getEstado() != 1) {
                        JOptionPane.showMessageDialog(this, "Usuário atualmente desativado, entre em contato com a gerência!");
                        return;
                    }

                    Usuario usuarioValidado = usuarioEncontrado;
                    JOptionPane.showMessageDialog(this, "Bem vindo, " + usuarioValidado.getNomeUsuario() + "!");
                    new MenuInicial(usuarioValidado);
                    this.dispose();

                } else {
                    JOptionPane.showMessageDialog(this, "Usuário ou senha incorretos!!");
                }
            } else {
                JOptionPane.showMessageDialog(this, "Usuário ou senha incorretos!!");
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Crachá deve conter apenas Numeros");
        }
    }


    public static void main(String[] args) {
        new Login();
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel1 = new JPanel();
        panel1.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(3, 2, new Insets(5, 5, 5, 5), 0, -1));
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(5, 1, new Insets(0, 0, 0, 0), -1, -1));
        panel1.add(panel2, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 2, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        usuarioCracha = new JLabel();
        Font usuarioCrachaFont = this.$$$getFont$$$(null, Font.BOLD, 22, usuarioCracha.getFont());
        if (usuarioCrachaFont != null) usuarioCracha.setFont(usuarioCrachaFont);
        usuarioCracha.setText("Crachá:");
        panel2.add(usuarioCracha, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        senhaLabel = new JLabel();
        Font senhaLabelFont = this.$$$getFont$$$(null, Font.BOLD, 22, senhaLabel.getFont());
        if (senhaLabelFont != null) senhaLabel.setFont(senhaLabelFont);
        senhaLabel.setText("Senha:");
        panel2.add(senhaLabel, new com.intellij.uiDesigner.core.GridConstraints(2, 0, 2, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        usuarioTF = new JTextField();
        usuarioTF.setText("");
        usuarioTF.setToolTipText("Número de Crachá");
        panel2.add(usuarioTF, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_NORTHWEST, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, 30), new Dimension(-1, 30), 0, false));
        senhaTF = new JPasswordField();
        senhaTF.setToolTipText("Senha");
        panel2.add(senhaTF, new com.intellij.uiDesigner.core.GridConstraints(4, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, 30), new Dimension(-1, 30), 0, false));
        EntrarBT = new JButton();
        EntrarBT.setText("Entrar");
        panel1.add(EntrarBT, new com.intellij.uiDesigner.core.GridConstraints(2, 0, 1, 2, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(614, 30), null, 0, false));
        cadastrarLabel = new JLabel();
        cadastrarLabel.setText("Não tem uma conta ainda? Cadastrar!");
        panel1.add(cadastrarLabel, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
        if (currentFont == null) return null;
        String resultName;
        if (fontName == null) {
            resultName = currentFont.getName();
        } else {
            Font testFont = new Font(fontName, Font.PLAIN, 10);
            if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
                resultName = fontName;
            } else {
                resultName = currentFont.getName();
            }
        }
        Font font = new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
        boolean isMac = System.getProperty("os.name", "").toLowerCase(Locale.ENGLISH).startsWith("mac");
        Font fontWithFallback = isMac ? new Font(font.getFamily(), font.getStyle(), font.getSize()) : new StyleContext().getFont(font.getFamily(), font.getStyle(), font.getSize());
        return fontWithFallback instanceof FontUIResource ? fontWithFallback : new FontUIResource(fontWithFallback);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }
}